development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fancy_development
  pool: 5
  username: root
  password: rails

production:
  adapter: mysql2
  database: fancy_production
  username: root
  password: rails
  encoding: utf8
  pool: 5