development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fancy_development
  pool: 5
  username: root
  password: rails

production:
  adapter: mysql2
  encoding: utf8
  database: test_task
  username: root
  password: "140283"